"""Model module - imports from palace.registry.sqlalchemy.model for backward compatibility."""

from __future__ import annotations

# Import everything from the new package location
from palace.registry.sqlalchemy.model import (
    Admin,
    Audience,
    Base,
    CollectionSummary,
    ConfigurationSetting,
    DelegatedPatronIdentifier,
    ExternalIntegration,
    Hyperlink,
    Library,
    LibraryAlias,
    LibraryType,
    Place,
    PlaceAlias,
    Resource,
    ServiceArea,
    SessionManager,
    ShortClientTokenDecoder,
    Validation,
    create,
    dump_query,
    generate_secret,
    get_one,
    get_one_or_create,
    libraries_audiences,
    production_session,
)

__all__ = [
    "Admin",
    "Audience",
    "Base",
    "CollectionSummary",
    "ConfigurationSetting",
    "DelegatedPatronIdentifier",
    "ExternalIntegration",
    "Hyperlink",
    "Library",
    "LibraryAlias",
    "LibraryType",
    "Place",
    "PlaceAlias",
    "Resource",
    "ServiceArea",
    "SessionManager",
    "ShortClientTokenDecoder",
    "Validation",
    "create",
    "dump_query",
    "generate_secret",
    "get_one",
    "get_one_or_create",
    "libraries_audiences",
    "production_session",
]
