[tool.poetry]
name = "library-registry"
version = "0.0"
description = ""
license = "Apache-2.0"
authors = ["The Palace Project <info@thepalaceproject.org>"]

[tool.poetry.dependencies]
python = ">=3.6"
feedparser = "*"
loggly-python-handler = "*"
lxml = "*"
psycopg2 = { version = "*", optional = true }
psycopg2-binary = { version = "*", optional = true }
maxminddb-geolite2 = "*"
requests = "*"
pycryptodome = "*"
uszipcode = "==0.2.4"
Flask = "*"
Flask-Bcrypt = "*"
Flask-SQLAlchemy-Session = "*"
Flask-Babel = "*"
GeoAlchemy2 = "*"
PyJWT = "*"
SQLAlchemy = "==1.3.23"
Pillow = "*"
bcrypt = "*"
gunicorn = "*"
aws-xray-sdk = "<2.9"

[tool.poetry.extras]
pg = ["psycopg2"]
pg-binary = ["psycopg2-binary"]

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-datadir = "*"
flake8 = "*"
black = "*"
isort = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
