[tool.poetry]
name = "library-registry"
version = "0" # Version number is managed with tags in git
description = "The Palace Project library registry"
homepage = "https://thepalaceproject.org"
license = "Apache-2.0"
authors = ["The Palace Project <info@thepalaceproject.org>"]
readme = "README.md"
repository = "https://github.com/ThePalaceProject/library-registry"

[tool.isort]
profile = "black"

[tool.poetry.dependencies]
python = ">=3.6.1"
feedparser = "*"
loggly-python-handler = "*"
lxml = "*"
psycopg2 = { version = "*", optional = true }
psycopg2-binary = { version = "*", optional = true }
maxminddb-geolite2 = "*"
requests = "*"
pycryptodome = "*"
uszipcode = "==0.2.4"
Flask = "*"
Flask-Bcrypt = "*"
Flask-SQLAlchemy-Session = "*"
Flask-Babel = "*"
GeoAlchemy2 = "*"
PyJWT = "*"
SQLAlchemy = "==1.3.23"
Pillow = "*"
bcrypt = "*"
gunicorn = "*"
aws-xray-sdk = "<2.9"

[tool.poetry.extras]
pg = ["psycopg2"]
pg-binary = ["psycopg2-binary"]

[tool.poetry.dev-dependencies]
pytest = "^6"
pytest-datadir = "*"
pytest-timeout = "*"
pre-commit = "~2.16"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
timeout = "600"
timeout_method = "thread"
