"""Remove library logo

Revision ID: 7dc7590e1819
Revises: 9b462df21780
Create Date: 2023-04-28 07:20:50.401126+00:00

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7dc7590e1819"
down_revision = "9b462df21780"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("libraries", "logo")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "libraries", sa.Column("logo", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
