"""Library logo url

Revision ID: aa6b44e2e879
Revises:
Create Date: 2022-11-28 08:41:40.026366+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aa6b44e2e879"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("libraries", sa.Column("logo_url", sa.Unicode(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("libraries", "logo_url")
    # ### end Alembic commands ###
