FROM postgis/postgis:9.6-3.1

ENV POSTGRES_PASSWORD="password"
ENV POSTGRES_USER="postgres"

COPY ./postgis_init.sh /docker-entrypoint-initdb.d/postgis-init.sh

EXPOSE 5432

VOLUME ["/var/lib/postgresql/data"]
