name: Test Library Registry & Build Docker Image
on: [push, pull_request]
env:
  POSTGRES_USER: simplified_test
  POSTGRES_PASSWORD: test
  POSTGRES_DB: simplified_registry_test
  SIMPLIFIED_TEST_DATABASE: postgresql://simplified_test:test@localhost:5432/simplified_registry_test

jobs:
  test-library-registry:
    name: Run Library Registry tests
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. This prevents duplicated runs on internal PRs.
    # Some discussion of this here:
    # https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    services:
      postgres:
        image: postgis/postgis:12-3.1
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python Packages
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install

      - name: Run Tests
        run: pipenv run pytest -x tests


  container-build-enabled:
    # Don't build container unless the DOCKER_REGISTRY_HOST secret is set.
    name: Should container be built and pushed?
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.DOCKER_REGISTRY_HOST }}
    outputs:
      enabled: ${{ steps.set-build-enabled.outputs.build_enabled }}
    steps:
      - id: set-build-enabled
        run: echo "::set-output name=build_enabled::${{ toJSON(env.REGISTRY != null) }}"


  build-docker-library-registry:
    name: Build and push library-registry docker image
    runs-on: ubuntu-latest
    needs:
      - test-library-registry
      - container-build-enabled

    # Only build docker containers on a branch push. PRs are run in the context of the repository from
    # which they are made, so they don't have the secrets necessary to push to the docker registry.
    # Also, don't run unless build/push is enabled.
    if: github.event_name == 'push' && fromJSON(needs.container-build-enabled.outputs.enabled)

    env:
      REGISTRY_HOST: ${{ secrets.DOCKER_REGISTRY_HOST }}

    steps:
      # If we're using GitHub Container Registry, we'll use some defaults.
      # Otherwise, we'll use secrets from the repository.
      - name: Setup Job Environment Variables
        run: |
          if [[ $REGISTRY_HOST == 'ghcr.io' ]]; then
            echo "REGISTRY_ACCOUNT=${{ github.repository_owner }}" >> "$GITHUB_ENV"
            echo "REGISTRY_USERNAME=${{ github.repository_owner }}" >> "$GITHUB_ENV"
            echo "REGISTRY_PASSWORD=${{ secrets.GITHUB_TOKEN }}" >> "$GITHUB_ENV"
          else
            echo "REGISTRY_ACCOUNT=${{ secrets.DOCKER_REGISTRY_ACCOUNT }}" >> "$GITHUB_ENV"
            echo "REGISTRY_USERNAME=${{ secrets.DOCKER_REGISTRY_USERNAME }}" >> "$GITHUB_ENV"
            echo "REGISTRY_PASSWORD=${{ secrets.DOCKER_REGISTRY_TOKEN }}" >> "$GITHUB_ENV"
          fi

      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Generate tags for library-registry image
        id: library-registry-tags
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ${{ env.REGISTRY_HOST }}/${{ env.REGISTRY_ACCOUNT }}/library-registry
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Build and push library-registry image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          target: libreg_prod
          push: true
          tags: ${{ steps.library-registry-tags.outputs.tags }}
